#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class CaptureElement;
                ref class ComboBox;
            }
        }
    }
}

namespace SDKTemplate
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario1_PreviewSettings : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::CaptureElement^ PreviewBuffer2;
        private: ::Windows::UI::Xaml::Controls::CaptureElement^ PreviewBuffer1;
        private: ::Windows::UI::Xaml::Controls::CaptureElement^ PreviewControl2;
        private: ::Windows::UI::Xaml::Controls::CaptureElement^ PreviewControl1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ CameraSettings1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ EnumedDeviceList1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ CameraSettings2;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ EnumedDeviceList2;
    };
}

